# Generated by Django 4.2.7 on 2023-11-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='Resource')),
                ('resource_name', models.TextField(blank=True, null=True, verbose_name='Resource Name')),
                ('resource_link', models.TextField(blank=True, null=True, verbose_name='Resource Link')),
                ('resource_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video'), ('link', 'Link')], max_length=20, verbose_name='Resource Type')),
                ('resource_duration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Resource Duration/Length')),
                ('transcribed_text', models.TextField(null=True, verbose_name='Transcribed Text')),
                ('transcription_language', models.CharField(max_length=50, verbose_name='Transcription Language')),
                ('enable_speaker_recognition', models.BooleanField(default=False, verbose_name='Enable Speaker Recognition?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transcription',
                'verbose_name_plural': 'Transcriptions',
            },
        ),
    ]
